# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: vext.info
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
 ... standing on the shoulders of giants...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 0xvext
github_username:  0xvext
remote_theme: mmistakes/minimal-mistakes

# Build settings
markdown: kramdown
#theme: minima
#theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "default", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
#  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ["_pages"]

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: false
      related: true
      author_profile: true

locale: "en-US"
name: vext
search: true

author:
  name   : "vext"
  avatar : "/assets/images/vext-cropped.png"
  bio    : "Hacker. Nerd. InfoSec pro. Armchair lawyer. Certifiable. Breaks things to rebuild them better. Understands opex decisions, but resents them. Bleeds purple."
  twitter : 0xvext
  github : 0xvext
#  email  : # optional
#  uri    : "http://your-site.com"
#  home   : # null (default), "absolute or relative url to link to author home"

paginate: 100 # amount of posts to show
paginate_path: /page:num/
